insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-01-2016', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-02-2016', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-03-2016', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-04-2016', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-05-2016', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-06-2016', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-07-2016', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-08-2016', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-09-2016', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-10-2016', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-11-2016', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-12-2016', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-01-2017', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-02-2017', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-03-2017', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-04-2017', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-05-2017', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-06-2017', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-07-2017', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-08-2017', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-09-2017', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-10-2017', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-11-2017', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-12-2017', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-01-2018', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-02-2018', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-03-2018', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-04-2018', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-05-2018', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-06-2018', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-07-2018', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-08-2018', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-09-2018', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-10-2018', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-11-2018', '%d-%m-%Y'));
insert into BudgetApp.Time_Period (budget_month) values (STR_TO_DATE('01-12-2018', '%d-%m-%Y'));

insert into BudgetApp.User (user_name,password) values ('Sunil',"sunhar143");
insert into BudgetApp.User (user_name,password) values ('Harshita',"sunhar143");

insert into BudgetApp.Category (category_name,default_amount,is_basic) values ('Rent',1400,1);
insert into BudgetApp.Category (category_name,default_amount,is_basic) values ('PGE',85,1);
insert into BudgetApp.Category (category_name,default_amount,is_basic) values ('NG',15,1);
insert into BudgetApp.Category (category_name,default_amount,is_basic) values ('Phone',100,1);
insert into BudgetApp.Category (category_name,default_amount,is_basic) values ('InternetSlingNetflix',125,1);
insert into BudgetApp.Category (category_name,default_amount,is_basic) values ('Food_Ind',75,1);
insert into BudgetApp.Category (category_name,default_amount,is_basic) values ('Food_GS',200,1);
insert into BudgetApp.Category (category_name,default_amount,is_basic) values ('Other',0,0);